export interface USState {
  code: string;
  name: string;
  // Nombre en inglés — usado para cruzar con resultados de APIs de geocodificación.
  enName: string;
}

export const US_STATES: USState[] = [
  { code: "AL", name: "Alabama", enName: "Alabama" },
  { code: "AK", name: "Alaska", enName: "Alaska" },
  { code: "AZ", name: "Arizona", enName: "Arizona" },
  { code: "AR", name: "Arkansas", enName: "Arkansas" },
  { code: "CA", name: "California", enName: "California" },
  { code: "CO", name: "Colorado", enName: "Colorado" },
  { code: "CT", name: "Connecticut", enName: "Connecticut" },
  { code: "DE", name: "Delaware", enName: "Delaware" },
  { code: "DC", name: "Distrito de Columbia", enName: "District of Columbia" },
  { code: "FL", name: "Florida", enName: "Florida" },
  { code: "GA", name: "Georgia", enName: "Georgia" },
  { code: "HI", name: "Hawái", enName: "Hawaii" },
  { code: "ID", name: "Idaho", enName: "Idaho" },
  { code: "IL", name: "Illinois", enName: "Illinois" },
  { code: "IN", name: "Indiana", enName: "Indiana" },
  { code: "IA", name: "Iowa", enName: "Iowa" },
  { code: "KS", name: "Kansas", enName: "Kansas" },
  { code: "KY", name: "Kentucky", enName: "Kentucky" },
  { code: "LA", name: "Luisiana", enName: "Louisiana" },
  { code: "ME", name: "Maine", enName: "Maine" },
  { code: "MD", name: "Maryland", enName: "Maryland" },
  { code: "MA", name: "Massachusetts", enName: "Massachusetts" },
  { code: "MI", name: "Michigan", enName: "Michigan" },
  { code: "MN", name: "Minnesota", enName: "Minnesota" },
  { code: "MS", name: "Misisipi", enName: "Mississippi" },
  { code: "MO", name: "Misuri", enName: "Missouri" },
  { code: "MT", name: "Montana", enName: "Montana" },
  { code: "NE", name: "Nebraska", enName: "Nebraska" },
  { code: "NV", name: "Nevada", enName: "Nevada" },
  { code: "NH", name: "New Hampshire", enName: "New Hampshire" },
  { code: "NJ", name: "Nueva Jersey", enName: "New Jersey" },
  { code: "NM", name: "Nuevo México", enName: "New Mexico" },
  { code: "NY", name: "Nueva York", enName: "New York" },
  { code: "NC", name: "Carolina del Norte", enName: "North Carolina" },
  { code: "ND", name: "Dakota del Norte", enName: "North Dakota" },
  { code: "OH", name: "Ohio", enName: "Ohio" },
  { code: "OK", name: "Oklahoma", enName: "Oklahoma" },
  { code: "OR", name: "Oregón", enName: "Oregon" },
  { code: "PA", name: "Pensilvania", enName: "Pennsylvania" },
  { code: "RI", name: "Rhode Island", enName: "Rhode Island" },
  { code: "SC", name: "Carolina del Sur", enName: "South Carolina" },
  { code: "SD", name: "Dakota del Sur", enName: "South Dakota" },
  { code: "TN", name: "Tennessee", enName: "Tennessee" },
  { code: "TX", name: "Texas", enName: "Texas" },
  { code: "UT", name: "Utah", enName: "Utah" },
  { code: "VT", name: "Vermont", enName: "Vermont" },
  { code: "VA", name: "Virginia", enName: "Virginia" },
  { code: "WA", name: "Washington", enName: "Washington" },
  { code: "WV", name: "Virginia Occidental", enName: "West Virginia" },
  { code: "WI", name: "Wisconsin", enName: "Wisconsin" },
  { code: "WY", name: "Wyoming", enName: "Wyoming" },
];
